// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/auth-study.proto

package authstudy

import (
	fmt "fmt"
	proto "google.golang.org/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/asim/go-micro/v3/api"
	client "github.com/asim/go-micro/v3/client"
	server "github.com/asim/go-micro/v3/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for AuthStudy service

func NewAuthStudyEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for AuthStudy service

type AuthStudyService interface {
	Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (AuthStudy_StreamService, error)
	PingPong(ctx context.Context, opts ...client.CallOption) (AuthStudy_PingPongService, error)
}

type authStudyService struct {
	c    client.Client
	name string
}

func NewAuthStudyService(name string, c client.Client) AuthStudyService {
	return &authStudyService{
		c:    c,
		name: name,
	}
}

func (c *authStudyService) Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "AuthStudy.Call", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authStudyService) Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (AuthStudy_StreamService, error) {
	req := c.c.NewRequest(c.name, "AuthStudy.Stream", &StreamingRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	if err := stream.Send(in); err != nil {
		return nil, err
	}
	return &authStudyServiceStream{stream}, nil
}

type AuthStudy_StreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Recv() (*StreamingResponse, error)
}

type authStudyServiceStream struct {
	stream client.Stream
}

func (x *authStudyServiceStream) Close() error {
	return x.stream.Close()
}

func (x *authStudyServiceStream) Context() context.Context {
	return x.stream.Context()
}

func (x *authStudyServiceStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *authStudyServiceStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *authStudyServiceStream) Recv() (*StreamingResponse, error) {
	m := new(StreamingResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

func (c *authStudyService) PingPong(ctx context.Context, opts ...client.CallOption) (AuthStudy_PingPongService, error) {
	req := c.c.NewRequest(c.name, "AuthStudy.PingPong", &Ping{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &authStudyServicePingPong{stream}, nil
}

type AuthStudy_PingPongService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Ping) error
	Recv() (*Pong, error)
}

type authStudyServicePingPong struct {
	stream client.Stream
}

func (x *authStudyServicePingPong) Close() error {
	return x.stream.Close()
}

func (x *authStudyServicePingPong) Context() context.Context {
	return x.stream.Context()
}

func (x *authStudyServicePingPong) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *authStudyServicePingPong) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *authStudyServicePingPong) Send(m *Ping) error {
	return x.stream.Send(m)
}

func (x *authStudyServicePingPong) Recv() (*Pong, error) {
	m := new(Pong)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for AuthStudy service

type AuthStudyHandler interface {
	Call(context.Context, *Request, *Response) error
	Stream(context.Context, *StreamingRequest, AuthStudy_StreamStream) error
	PingPong(context.Context, AuthStudy_PingPongStream) error
}

func RegisterAuthStudyHandler(s server.Server, hdlr AuthStudyHandler, opts ...server.HandlerOption) error {
	type authStudy interface {
		Call(ctx context.Context, in *Request, out *Response) error
		Stream(ctx context.Context, stream server.Stream) error
		PingPong(ctx context.Context, stream server.Stream) error
	}
	type AuthStudy struct {
		authStudy
	}
	h := &authStudyHandler{hdlr}
	return s.Handle(s.NewHandler(&AuthStudy{h}, opts...))
}

type authStudyHandler struct {
	AuthStudyHandler
}

func (h *authStudyHandler) Call(ctx context.Context, in *Request, out *Response) error {
	return h.AuthStudyHandler.Call(ctx, in, out)
}

func (h *authStudyHandler) Stream(ctx context.Context, stream server.Stream) error {
	m := new(StreamingRequest)
	if err := stream.Recv(m); err != nil {
		return err
	}
	return h.AuthStudyHandler.Stream(ctx, m, &authStudyStreamStream{stream})
}

type AuthStudy_StreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*StreamingResponse) error
}

type authStudyStreamStream struct {
	stream server.Stream
}

func (x *authStudyStreamStream) Close() error {
	return x.stream.Close()
}

func (x *authStudyStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *authStudyStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *authStudyStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *authStudyStreamStream) Send(m *StreamingResponse) error {
	return x.stream.Send(m)
}

func (h *authStudyHandler) PingPong(ctx context.Context, stream server.Stream) error {
	return h.AuthStudyHandler.PingPong(ctx, &authStudyPingPongStream{stream})
}

type AuthStudy_PingPongStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Pong) error
	Recv() (*Ping, error)
}

type authStudyPingPongStream struct {
	stream server.Stream
}

func (x *authStudyPingPongStream) Close() error {
	return x.stream.Close()
}

func (x *authStudyPingPongStream) Context() context.Context {
	return x.stream.Context()
}

func (x *authStudyPingPongStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *authStudyPingPongStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *authStudyPingPongStream) Send(m *Pong) error {
	return x.stream.Send(m)
}

func (x *authStudyPingPongStream) Recv() (*Ping, error) {
	m := new(Ping)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}
